print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "L:/Jess/Enjo/Repos/V2/Enjo/Enjo/Assets/3DModels/Environment/ApothecaryStore.ma"`)
{		
	file -o "L:/Jess/Enjo/Repos/V2/Enjo/Enjo/Assets/3DModels/Environment/ApothecaryStore.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "L:/Jess/Enjo/Repos/V2/Enjo/Enjo/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "L:/Jess/Enjo/Repos/V2/Enjo/Enjo/Temp/CommandPipe";

$donepipeKill = `fopen "L:/Jess/Enjo/Repos/V2/Enjo/Enjo/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
